apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-app
    type: jokes
spec:
  containers:
    - name: jokes-kn-container
      image: iarpitsrivastava06/jokes-kubernetes-test:v3      
               
