apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    name: my-app
    type: jokes
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-app
        type: jokes
    spec:
      containers:
        - name: jokes-kn-container
          image: iarpitsrivastava06/jokes-kubernetes-test:v3
  replicas: 3        