apiVersion: v1
kind: ReplicationController
metadata:
  name: my-jokes-rc
  labels:
    app: my_jokes_app_rc
    type: jokes-app
spec:
  template:
    metadata:
      name: my-jokes-pod
      labels:
        app: my_jokes_app_pod
        type: jokes-app
    spec:
      containers:
      - name: jokes-kn-cn
        image: iarpitsrivastava06/jokes-kubernetes-test:v2
  replicas: 3