apiVersion: v1
kind: Service
metadata:
  name: my-jokes-service
  labels:
    app: my_jokes_service
    type: jokes_app
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8081
      nodePort: 30008
  selector: 
    type: jokes-app    
