POST http://localhost:8080/person
Content-Type: application/json

{
  "id": 1,
  "firstName": "Arpit",
  "lastName": "Srivastava",
  "age": 23,
  "email": "abc@xyz.com",
  "balance": 123.00,
  "password": "abcdef",
  "mobileNumber": 1
  }

###

PUT http://localhost:8080/person/addMoney?amount=1000&mobileNumber=1
Content-Type: application/json

###
